include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Enforce good coding practices
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - avoid_print
    - prefer_single_quotes
    - always_declare_return_types
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  
  errors:
    # Treat these as warnings instead of errors during development
    missing_required_param: warning
    missing_return: warning