// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8LkUl2-HwBPpC5YsnhsipOpLIvYV3Cpg',
    appId: '1:331669988324:web:040ca02aaaffe285ad9df1',
    messagingSenderId: '331669988324',
    projectId: 'garageguru-8438b',
    authDomain: 'garageguru-8438b.firebaseapp.com',
    databaseURL: 'https://garageguru-8438b-default-rtdb.firebaseio.com',
    storageBucket: 'garageguru-8438b.firebasestorage.app',
    measurementId: 'G-98T6R4NK5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW1dzXs0gGsGV7TvSQBJrEXtL07t8GQo8',
    appId: '1:331669988324:android:6c4c25444b2a72f6ad9df1',
    messagingSenderId: '331669988324',
    projectId: 'garageguru-8438b',
    databaseURL: 'https://garageguru-8438b-default-rtdb.firebaseio.com',
    storageBucket: 'garageguru-8438b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpuPpiXMsaHucqaRlk7qCEeEOqxfZ8DFw',
    appId: '1:331669988324:ios:dee6c7cdaa55591fad9df1',
    messagingSenderId: '331669988324',
    projectId: 'garageguru-8438b',
    databaseURL: 'https://garageguru-8438b-default-rtdb.firebaseio.com',
    storageBucket: 'garageguru-8438b.firebasestorage.app',
    iosClientId: '331669988324-ogtm1min3ea797nhpsqaoevettqmkdbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.garageGuru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpuPpiXMsaHucqaRlk7qCEeEOqxfZ8DFw',
    appId: '1:331669988324:ios:dee6c7cdaa55591fad9df1',
    messagingSenderId: '331669988324',
    projectId: 'garageguru-8438b',
    databaseURL: 'https://garageguru-8438b-default-rtdb.firebaseio.com',
    storageBucket: 'garageguru-8438b.firebasestorage.app',
    iosClientId: '331669988324-ogtm1min3ea797nhpsqaoevettqmkdbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.garageGuru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8LkUl2-HwBPpC5YsnhsipOpLIvYV3Cpg',
    appId: '1:331669988324:web:5397be2ffc2b2eecad9df1',
    messagingSenderId: '331669988324',
    projectId: 'garageguru-8438b',
    authDomain: 'garageguru-8438b.firebaseapp.com',
    databaseURL: 'https://garageguru-8438b-default-rtdb.firebaseio.com',
    storageBucket: 'garageguru-8438b.firebasestorage.app',
    measurementId: 'G-LJ4WHQVZ3P',
  );
}
